# Generated by Django 5.1.4 on 2025-03-18 08:40

import backend.custom.functions
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Xóa')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ngày xóa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Tên người dùng')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Thư điện tử')),
                ('email_verified', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Số điện thoại')),
                ('phone_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Họ')),
                ('last_name', models.CharField(max_length=100, verbose_name='Tên')),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=10, null=True, verbose_name='Giới tính')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Sinh nhật')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=backend.custom.functions.upload_to, verbose_name='Ảnh đại diện')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('public', models.BooleanField(default=True, verbose_name='Công khai')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Nguời xóa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'tb_app_account_user',
                'ordering': ['date_joined'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Xóa')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ngày xóa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự hiển thị')),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, verbose_name='Slug')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('expires', models.DateTimeField(verbose_name='Hạn sử dụng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Nguời xóa')),
                ('permissions', models.ManyToManyField(blank=True, related_name='APIKey_permission', to='auth.permission', verbose_name='Quyền truy cập')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Key',
                'db_table': 'tb_app_account_apikey',
                'ordering': ['order', 'created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='APIKeyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=1000, verbose_name='Tên')),
                ('des', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app_account.apikey')),
            ],
            options={
                'verbose_name': 'API Key Translation',
                'db_table': 'tb_app_account_apikey_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
