# Generated by Django 5.1.4 on 2025-03-19 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyEmail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifyemail_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mã email',
                'verbose_name_plural': 'Mã email',
                'db_table': 'tb_app_account_verify_mail',
            },
        ),
    ]
