# Generated by Django 5.1.4 on 2025-03-11 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='APIKey_permission', to='auth.permission', verbose_name='Quyền truy cập'),
        ),
        migrations.AlterModelTable(
            name='apikey',
            table='tb_app_account_apikey',
        ),
        migrations.AlterModelTable(
            name='apikeytranslation',
            table='tb_app_account_apikey_translation',
        ),
    ]
